//! Cross-language compatibility: RustCrypt must decrypt every value produced
//! by GoCrypt, the family's reference implementation.
//!
//! The golden vectors live in `tests/fixtures/gocrypt_vectors.json` and are
//! generated by `scripts/gen-vectors` (Go). The `#[ignore]`d tests at the
//! bottom additionally shell out to a real `gocrypt-cli` binary; run them with
//!
//! ```text
//! GOCRYPT_CLI=/path/to/gocrypt-cli cargo test --test cross_language -- --ignored
//! ```

use std::env;
use std::path::PathBuf;
use std::process::Command;

use rustcrypt_jasypt::{Encryptor, JasyptEncryptor, JasyptStrongEncryptor, StringEncryptor};
use serde::Deserialize;

const FIXTURE: &str = include_str!("fixtures/gocrypt_vectors.json");

#[derive(Deserialize)]
struct Fixture {
    gocrypt_commit: String,
    password: String,
    vectors: Vec<Vector>,
}

#[derive(Deserialize)]
struct Vector {
    mode: String,
    plaintext: String,
    encrypted: String,
}

fn fixture() -> Fixture {
    serde_json::from_str(FIXTURE).expect("fixture parses")
}

const MODES: [(&str, Option<&str>); 3] = [
    ("default", None),
    ("jasypt", Some("--jasypt")),
    ("jasypt-strong", Some("--jasypt-strong")),
];

fn encryptor_for(mode: &str, password: &str) -> Box<dyn StringEncryptor> {
    match mode {
        "default" => Box::new(Encryptor::new(password).unwrap()),
        "jasypt" => Box::new(JasyptEncryptor::new(password).unwrap()),
        "jasypt-strong" => Box::new(JasyptStrongEncryptor::new(password).unwrap()),
        other => panic!("unknown mode {other}"),
    }
}

#[test]
fn fixture_metadata_is_present() {
    let f = fixture();
    assert_eq!(f.gocrypt_commit.len(), 40, "full gocrypt commit hash");
    assert_eq!(f.password, "rustcrypt-test-2026");
}

#[test]
fn fixture_covers_all_modes_and_plaintexts() {
    let f = fixture();
    for (mode, _) in MODES {
        let plaintexts: Vec<&str> = f
            .vectors
            .iter()
            .filter(|v| v.mode == mode)
            .map(|v| v.plaintext.as_str())
            .collect();
        assert!(plaintexts.contains(&"hello"), "{mode}: hello");
        assert!(plaintexts.contains(&"Password123!"), "{mode}: Password123!");
        assert!(
            plaintexts.contains(&"Selamat pagi, Fariz 🦀"),
            "{mode}: UTF-8 sample"
        );
        assert!(
            plaintexts.iter().any(|p| p.chars().count() == 200),
            "{mode}: 200-char sample"
        );
    }
}

#[test]
fn decrypts_every_gocrypt_vector() {
    let f = fixture();
    assert!(!f.vectors.is_empty());
    for v in &f.vectors {
        let enc = encryptor_for(&v.mode, &f.password);
        let got = enc.decrypt_prefixed(&v.encrypted).unwrap_or_else(|err| {
            panic!(
                "mode={} plaintext={:?}: failed to decrypt GoCrypt value: {err}",
                v.mode, v.plaintext
            )
        });
        assert_eq!(got, v.plaintext, "mode={}", v.mode);
    }
}

#[test]
fn gocrypt_vectors_are_not_cross_mode_compatible() {
    // Sanity check that the fixture exercises three genuinely different
    // formats: a Jasypt value must not decrypt as AES-GCM and vice versa.
    let f = fixture();
    let gcm = Encryptor::new(&f.password).unwrap();
    let des = JasyptEncryptor::new(&f.password).unwrap();
    for v in &f.vectors {
        match v.mode.as_str() {
            "jasypt" | "jasypt-strong" => assert!(gcm.decrypt_prefixed(&v.encrypted).is_err()),
            "default" => assert_ne!(
                des.decrypt_prefixed(&v.encrypted).ok().as_deref(),
                Some(v.plaintext.as_str())
            ),
            _ => {}
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Live round trips against gocrypt-cli (ignored by default)
// ─────────────────────────────────────────────────────────────────────────────

fn gocrypt_cli() -> Option<PathBuf> {
    if let Some(p) = env::var_os("GOCRYPT_CLI") {
        let p = PathBuf::from(p);
        return p.is_file().then_some(p);
    }
    let path = env::var_os("PATH")?;
    env::split_paths(&path)
        .flat_map(|dir| ["gocrypt-cli", "gocrypt-cli.exe"].map(|n| dir.join(n)))
        .find(|p| p.is_file())
}

fn run_gocrypt(cli: &PathBuf, args: &[&str]) -> String {
    let out = Command::new(cli)
        .args(args)
        .output()
        .expect("spawn gocrypt-cli");
    assert!(
        out.status.success(),
        "gocrypt-cli {:?} failed: {}",
        args,
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout)
        .expect("utf-8 stdout")
        .trim_end_matches(['\r', '\n'])
        .to_owned()
}

fn mode_args<'a>(base: &[&'a str], flag: Option<&'a str>) -> Vec<&'a str> {
    let mut v = base.to_vec();
    v.extend(flag);
    v
}

#[test]
#[ignore = "requires gocrypt-cli (set GOCRYPT_CLI or put it on PATH)"]
fn gocrypt_cli_decrypts_rustcrypt_output() {
    let Some(cli) = gocrypt_cli() else {
        eprintln!("skipped: gocrypt-cli not found");
        return;
    };
    let f = fixture();
    let plaintexts: Vec<&str> = f.vectors.iter().map(|v| v.plaintext.as_str()).collect();
    for (mode, flag) in MODES {
        let enc = encryptor_for(mode, &f.password);
        for pt in &plaintexts {
            let wrapped = enc.encrypt_with_prefix(pt).unwrap();
            let args = mode_args(&["decrypt", "-p", &f.password, "-v", &wrapped], flag);
            let got = run_gocrypt(&cli, &args);
            assert_eq!(
                &got, pt,
                "mode={mode}: gocrypt-cli must decrypt RustCrypt output"
            );
        }
    }
}

#[test]
#[ignore = "requires gocrypt-cli (set GOCRYPT_CLI or put it on PATH)"]
fn rustcrypt_decrypts_gocrypt_cli_output() {
    let Some(cli) = gocrypt_cli() else {
        eprintln!("skipped: gocrypt-cli not found");
        return;
    };
    let f = fixture();
    let plaintexts: Vec<&str> = f.vectors.iter().map(|v| v.plaintext.as_str()).collect();
    for (mode, flag) in MODES {
        let enc = encryptor_for(mode, &f.password);
        for pt in &plaintexts {
            let args = mode_args(&["encrypt", "-p", &f.password, "-v", pt], flag);
            let wrapped = run_gocrypt(&cli, &args);
            assert!(wrapped.starts_with("ENC("), "gocrypt-cli output: {wrapped}");
            let got = enc.decrypt_prefixed(&wrapped).unwrap();
            assert_eq!(
                &got, pt,
                "mode={mode}: RustCrypt must decrypt gocrypt-cli output"
            );
        }
    }
}
